import localFont from "next/font/local";
import "./globals.css";
import { DefaultHeader, DefaultFooter } from '@/components/MainLayout'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DefaultHeader />
        <main className="dark:bg-gray-900">
          {children}
        </main>
        <DefaultFooter />
      </body>
    </html>
  );
}
